### ISSUE TITLE
Unable to See Text

### ISSUE THREAD

**Issue by zanematthew** [arthur-fontaine/figtable#1]
In the third column over, press tab twice, theres an editable area, but when typed in, nothing appears.

<img width="655" alt="Screen Shot 2022-11-30 at 11 19 00 AM" src="https://user-images.githubusercontent.com/654712/204852063-7efb5928-f095-4796-bc74-d7d430c73380.png">

I've looked throughout the UI to confirm the text isn't white, or too large in size, but I don't see an area for font-size or color.

Text is in the box, I can copy/paste, but it is not viewable.

Please adjust the code base so we can see text within the box.

**Comment by arthur-fontaine** [comment]
I couldn't reproduce the issue, but I'm pretty sure it's a bug in the Figma [Input](https://www.figma.com/widget-docs/api/component-Input/) component ([see the related row](https://github.com/arthur-fontaine/figtable/blob/3e6f8d11a6cdde0e7c893be5bcaf9daf66f486fb/src/code.tsx#LL160C17-L160C17))
